version: "3"
services:
  mysql:
    image: "mysql:5"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "${FORWARD_MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: "nginx:latest"
    volumes:
      - ./:/var/www/html/
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "${APP_PORT:-80}:80"

  php:
    build:
      context: ./docker/php-5.6
      dockerfile: Dockerfile
    image: "php-custom:5.6-fpm"
    volumes:
      - ./:/var/www/html/

volumes:
  mysql-data:
    driver: local